version: '3'

services:
  web:
    restart: always
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - .db_data/db.sqlite3:/db.sqlite3
      - static_volume:/usr/src/app/jobs/staticfiles
    ports:
      - "8080:8080"

volumes:
  static_volume:
